### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by i11us0ry** [sangbobo/webserviceTest#1]
项目--maven-reimport后执行javac ClientRun.java出错

ClientRun.java:3: 错误: 程序包org.apache.cxf.jaxws.endpoint.dynamic不存在
import org.apache.cxf.jaxws.endpoint.dynamic.JaxWsDynamicClientFactory;
                                            ^
ClientRun.java:4: 错误: 程序包org.apache.cxf.endpoint不存在
import org.apache.cxf.endpoint.Client;
                              ^
ClientRun.java:11: 错误: 找不到符号
    JaxWsDynamicClientFactory dcf = JaxWsDynamicClientFactory.newInstance();
    ^
  符号:   类 JaxWsDynamicClientFactory
  位置: 类 ClientRun
ClientRun.java:11: 错误: 找不到符号
    JaxWsDynamicClientFactory dcf = JaxWsDynamicClientFactory.newInstance();
                                    ^
  符号:   变量 JaxWsDynamicClientFactory
  位置: 类 ClientRun
ClientRun.java:12: 错误: 程序包org.apache.cxf.endpoint不存在
    org.apache.cxf.endpoint.Client client = dcf.createClient("http://localhost:8080/service/hello?wsdl");
                           ^
5 个错误

**Comment by sangbobo** [comment]
我代码拉下来，试了一下，没问题呀

**Comment by i11us0ry** [comment]
我的步骤是，下载源码，idea打开，然后右键项目--maven-reimport，然后cmd执行javac ClientRun.java，不知道是哪个步骤错了，师傅可以把详细的操作发一下吗？谢谢

**Comment by sangbobo** [comment]
你用的jdk版本多少？如果是大于1.7的话，你把pom里的apache-cxf更改为最新的试一下
`<dependency>`
      `<groupId>org.apache.cxf</groupId>`
      `<artifactId>apache-cxf</artifactId>`
      `<version>3.5.0</version>`
      `<type>pom</type>`
`</dependency>`

**Comment by i11us0ry** [comment]
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

好的 我更新试试

**Comment by i11us0ry** [comment]
3.5.0还是同样报错### 太难了 - -

**Comment by sangbobo** [comment]
解决了吗？留个联系方式交流一下

**Comment by i11us0ry** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月24日(周五) 上午10:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sangbobo/webserviceTest] 运行出错 (Issue #1)




 
解决了吗？留个联系方式交流一下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by i11us0ry** [comment]
wx:seventnight

> 解决了吗？留个联系方式交流一下

**Comment by i11us0ry** [comment]
邮件发了二维码的 结果上github上没有 0 - 0

**Comment by sangbobo** [comment]
问题已解决。
原因：本地环境问题。
